# Generated by Django 2.2.5 on 2022-02-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220223_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_verity',
            new_name='email_verified',
        ),
    ]
