# Generated by Django 2.2.5 on 2022-02-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220224_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('github', 'github'), ('kakao', 'kakao')], default='email', max_length=10, null=True),
        ),
    ]
