# Generated by Django 2.2.5 on 2022-02-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20220212_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='name',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
