# Generated by Django 2.2.5 on 2022-02-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20220216_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guests',
            field=models.IntegerField(default=1),
        ),
    ]
